name: build
on: [push, pull_request]
jobs:
  run:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
            #- windows-latest
        ocaml-version:
          - 4.11.1
          - 4.10.1
          - 4.09.1
          - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam pin -n .
      - run: opam depext -yt lwd nottui nottui-lwt
      - run: opam install -t . --deps-only
      - run: opam install -y containers cbor js_of_ocaml js_of_ocaml-lwt
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
